# Generated by Django 2.2.27 on 2022-05-03 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('url', models.CharField(max_length=200)),
                ('headers', models.CharField(max_length=2000)),
                ('parameters', models.CharField(max_length=2000)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Type')),
            ],
        ),
    ]
