# Generated by Django 2.2.27 on 2022-05-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0002_auto_20220504_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='avatat',
            field=models.FileField(default='avatars/default.png', upload_to='avatars/', verbose_name='个人头像'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
