# Generated by Django 2.2.27 on 2022-05-04 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_login', '0003_auto_20220504_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='avatat',
            new_name='avatar',
        ),
    ]
